import { mkdirSync, existsSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { Logger } from "../shared/logger.js";
import type { HarnessConfig } from "./config.js";
import { requirementsPath, stepsJsonPath } from "./artifacts/types.js";
import { runRequirements } from "./agents/requirements.js";
import { parseRequirements, RequirementsParseError } from "./requirements-parser.js";

interface DeriveOptions {
  config: HarnessConfig;
  log: Logger;
  /** Re-derive: regenerate requirements.md (LLM) and steps.json even if they exist. */
  force?: boolean;
}

/**
 * Two-stage derivation, run whenever the step plan needs (re)building:
 *   1. spec.md → requirements.md   (LLM — the Requirements agent)
 *   2. requirements.md → steps.json (deterministic — parseRequirements)
 *
 * requirements.md is a reviewable, editable intermediate: it is regenerated by
 * the LLM only when missing or `force` is set, so hand-edits survive between runs.
 */
export async function deriveSteps({ config, log, force = false }: DeriveOptions): Promise<void> {
  const bucketDir = resolve(config.bucketDir);
  mkdirSync(bucketDir, { recursive: true });

  const requirements = requirementsPath(bucketDir);
  const stepsPath = stepsJsonPath(bucketDir);

  // ── Stage 1: spec.md → requirements.md (LLM) ──────────────────────
  if (!existsSync(requirements) || force) {
    log.info(`Generating requirements.md from spec.md → ${requirements}`);
    await runRequirements(config, log);
    if (!existsSync(requirements)) {
      throw new Error(
        `Requirements agent did not write ${requirements}. Inspect the agent log and re-run.`,
      );
    }
  } else {
    log.info(`Using existing requirements.md: ${requirements}`);
  }

  // ── Stage 2: requirements.md → steps.json (deterministic) ─────────
  const requirementsMarkdown = readFileSync(requirements, "utf-8");

  let steps;
  try {
    steps = parseRequirements(requirementsMarkdown);
  } catch (err) {
    if (err instanceof RequirementsParseError) {
      throw new Error(`Failed to parse requirements.md: ${err.message}`);
    }
    throw err;
  }

  writeFileSync(stepsPath, JSON.stringify({ steps }, null, 2) + "\n", "utf-8");
  log.info(`Derived ${steps.length} steps → ${stepsPath}`);
}
